services:
    Acounts:
        build: ../Acounts
        image: "s14321k/acounts:d1"
        container_name: Accounts-ms
        ports:
            - "8081:8081"
        deploy:
            resources:
                limits:
#                    cpus: "0.1"
                    memory: 500M
        networks:
            - s14321k
    Loans:
        image: "s14321k/loans:d1"
        container_name: Loans-ms
        build: ../Loans
        ports:
            - "8082:8082"
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: 500M
        networks:
            - s14321k
    Cards:
        image: "s14321k/cards:d1"
        container_name: cards-ms
        build: ../Cards
        ports:
            - "8083:8083"
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: 500M
        networks:
            - s14321k

networks:
    s14321k:
        driver: bridge